### ISSUE TITLE
Above Head Particles

### ISSUE THREAD

**Issue by ghost** [DSH105/SparkTrail#1]
Hi there!

I love the plugin, as do my players! Though I would really enjoy being able to put the particles above players, instead of through them.. I know that there is a way, I just can't seem to accomplish it...

Thanks for the help as always!
-Moose

**Comment by DSH105** [comment]
If you head over to the config.yml file into the `effects` section, you'll find something along the lines of what's [documented in the wiki](https://github.com/DSH105/SparkTrail/wiki/Configuration#wiki-effects-section). Setting the `effects.<type>.playType` to `ABOVE` will play the effect above players' heads :).

**Comment by DSH105** [comment]
If you need anything else, feel free to comment here ;3
