### ISSUE TITLE
[Feature Request] Add A Trail Selector.

### ISSUE THREAD

**Issue by CodeTheDev** [DSH105/SparkTrail#17]
Hey I was wondering if you could add a trail selector like the one that you have in your echopet plugin? Make it so you have an option to name and enable/disable and change the item icon in the config. I think this would make it a lot easier to find what trail you want instead of typing the command over and over again.

Can you please maybe take this into consideration? I think it would be a great idea but it depends on what you think because it's your plugin.
- zachman338

**Comment by DSH105** [comment]
It's already part of the plugin :).

**Comment by CodeTheDev** [comment]
Really? Ok that's great! I'm glad it is in the plugin. By the way I tried this plugin on my server for donation perks and everyone is giving me such good feedback! Keep up the good work! :)

**Comment by DSH105** [comment]
;D
